const preferences = {
    name: {
        long: "CHO Blood Donation Information Center",
        short: "CHO BloodInfo",
    },
    url: "https://blood-donation-forecasting.site/",
    contact: {
        email: "chocsjdmbulacan@gmail.com",
        mobile: "044-3077538",
        telephone: "(0X) - XXXX-XXXX",
    },
    address: {
        city: "San Jose del Monte",
        province: "Bulacan",
    },
    background: {
        color: "danger",
        accent: "info",
        variant: "dark",
        gradient: false ? "bg-gradient" : "",
    },
    palette: {
        excel: ['#9999ff', '#993366', '#ffffcc', '#ccffff', '#660066', '#ff8080', '#0066cc', '#ccccff', '#000080', '#ff00ff', '#ffff00', '#0000ff', '#800080', '#800000', '#008080', '#0000ff'],
        expo: ['#fbc01e', '#efe1a2', '#fa8716', '#be0204', '#640f10', '#7e13e3'],
        exhibit: ['#3399ff', '#69ffff', '#ccff33', '#3333ff', '#9933ff', '#ff33ff'],
        redviolet: ['#e32d91', '#c830cc', '#4ea6dc', '#4775e7', '#8971e1', '#d54773'],
        slipstream: ['#4e67c8', '#5eccf3', '#a7ea52', '#5dceaf', '#ff8021', '#f14124'],
        studio: ['#f7901e', '#fec60b', '#9fe62f', '#4ea5d1', '#1c4596', '#542d90'],
        urbanpop: ['#86ce24', '#00a2e6', '#fac810', '#7d8f8c', '#d06b20', '#958b8b'],
        vaportrail: ['#df2e28', '#fe801a', '#e9bf35', '#81bb42', '#32c7a9', '#4a9bdc'],
        verve: ['#ff388c', '#e40059', '#9c007f', '#68007f', '#005bd3', '#00349e'],
        waveform: ['#31b6fd', '#4584d3', '#5bd078', '#a5d028', '#f5c040', '#05e0db'],
    },
    options: {
        chc: {
            "": "City Health Center",
            1: "Assumption",
            2: "Bagong Buhay",
            3: "Bagong Buhay II",
            4: "Bagong Buhay III",
            5: "Citrus",
            6: "Ciudad Real",
            7: "Dulong Bayan",
            8: "Fatima",
            9: "Fatima II",
            10: "Fatima III",
            11: "Fatima IV",
            12: "Fatima V",
            13: "Francisco Homes-Guijo",
            14: "Francisco Homes-Mulawin",
            15: "Francisco Homes-Narra",
            16: "Francisco Homes-Yakal",
            17: "Gaya-Gaya",
            18: "Graceville",
            19: "Gumaoc Central",
            20: "Gumaoc East",
            21: "Gumaoc West",
            22: "Kaybanban",
            23: "Kaypian",
            24: "Lawang Pari",
            25: "Maharlika",
            26: "Minuyan",
            27: "Minuyan II",
            28: "Minuyan III",
            29: "Minuyan IV",
            30: "Minuyan Proper",
            31: "Minuyan V",
            32: "Muzon",
            33: "Paradise III",
            34: "Poblacion",
            35: "Poblacion I",
            36: "San Isidro",
            37: "San Manuel",
            38: "San Martin",
            39: "San Martin II",
            40: "San Martin III",
            41: "San Martin IV",
            42: "San Pedro",
            43: "San Rafael",
            44: "San Rafael I",
            45: "San Rafael III",
            46: "San Rafael IV",
            47: "San Rafael V",
            48: "San Roque",
            49: "Santa Cruz",
            50: "Santa Cruz II",
            51: "Santa Cruz III",
            52: "Santa Cruz IV",
            53: "Santa Cruz V",
            54: "Santo Cristo",
            55: "Santo Niño",
            56: "Santo Niño II",
            57: "Sapang Palay",
            58: "St. Martin de Porres",
            59: "Tungkong Mangga",
        },
        bloodbank: {
            "": "Bloodbank",
            1: "Bulacan Blood Center",
            2: "Philippine Heart Center",
            3: "Philippine Red Cross",
        },
        bloodtype: {
            "": "Bloodtype",
            1: "A+",
            2: "B+",
            3: "AB+",
            4: "O+",
            5: "A-",
            6: "B-",
            7: "AB-",
            8: "O-",
        },
    }
};

export default preferences;